Feat: Support Decline Payouts
spknetwork/3speak-legacy-studio pull request #17
Opened 2023-06-27 11:08 UTC by sag333ar

- Validate Post Beneficiaries
- Validate Decline Payout

2023-06-28 16:46 UTC, feruzm commented on routes/mobile/middleware-mobile.js
> +      const sagar = beneficiaries.filter((o) => o.account === "sagarkothari88");
@sag333ar This is beside encoder fees? Because video already has that info both beneficiary name and percents

2023-06-29 07:35 UTC, vaultec81 commented on routes/mobile/middleware-mobile.js
> +      const sagar = beneficiaries.filter((o) => o.account === "sagarkothari88");
Resolved separately

2023-06-29 07:40 UTC, vaultec81 requested changes

2023-06-29 07:40 UTC, vaultec81 commented on routes/mobile/middleware-mobile.js
> +        threespeakleader.length === 0
Looks like spkBeneficiary is missing? Should that be there?

2023-06-29 08:28 UTC, merged